# Aggregate info in CSV files generated by Imaris software

import pandas as pd
import os
import glob

A_COLOCAL_ROW = 5
B_COLOCAL_ROW = 6
PEARSON_DATASET_ROW = 11
PEARSON_COLOCAL_ROW = 13


path = os.getcwd()
print("*****************************************")
print("Current directory:", path);

A_colocal_vals = []
B_colocal_vals = []
Pearson_dataset_vals = []
Pearson_colocal_vals = []

csv_files = glob.glob(os.path.join(path, "*.csv"))

for f in csv_files:
    
    print("*****************************************")
    print('File Name:', f.split("/")[-1])
    
    df = pd.read_csv(f)
    entries = df.values.tolist()
    
    A_colocal_val = entries[A_COLOCAL_ROW][0].split(";")[1]
    A_colocal_vals.append(float(A_colocal_val))
    
    B_colocal_val = entries[B_COLOCAL_ROW][0].split(";")[1]
    B_colocal_vals.append(float(B_colocal_val))
    
    Pearson_dataset_val = entries[PEARSON_DATASET_ROW][0].split(";")[1]
    Pearson_dataset_vals.append(float(Pearson_dataset_val))
    
    Pearson_colocal_val = entries[PEARSON_COLOCAL_ROW][0].split(";")[1]
    Pearson_colocal_vals.append(float(Pearson_colocal_val))
    
    print(A_colocal_val, B_colocal_val, Pearson_dataset_val, Pearson_colocal_val)

print("*****************************************")
print("% of volume A above threshold colocalized")
for A_colocal_val in A_colocal_vals:
    print(A_colocal_val/100)
    
print("*****************************************")
print("% of volume B above threshold colocalized")
for B_colocal_val in B_colocal_vals:
    print(B_colocal_val/100)
    
print("*****************************************")
print("Pearson's coefficient in dataset volume")
for Pearson_dataset_val in Pearson_dataset_vals:
    print(Pearson_dataset_val)
    
print("*****************************************")
print("Pearson's coefficient in colocalized volume")
for Pearson_colocal_val in Pearson_colocal_vals:
    print(Pearson_colocal_val)  
    
